name: Lint

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set the correct Node version using nvm
        shell: bash -l {0}
        run: nvm install

      - name: cache npm downloads
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: yarn install
      - name: Lint
        run: yarn eslint
