name: Run tests

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set the correct Node version using nvm
        shell: bash -l {0}
        run: nvm install
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test
